disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - redundant_discardable_let
  - trailing_comma
  - type_name
  - identifier_name
opt_in_rules:
  - explicit_init
included:
  - Sources
  - Tests
excluded:
  - .build
